#!/usr/bin/env python3

import getpass

print("Input new password")
pw = getpass.getpass()
print("Repeat please")
if pw != getpass.getpass():
	print("Passwords do not match!")
else:

	from doreah import auth
	auth.defaultuser.setpw(pw)
